include $(GNUSTEP_MAKEFILES)/common.make
TOOL_NAME = Answer
Answer = calc.h sub.h add.h mul.h div.h result.h 
Answer_OBJC_FILES = main.m calc.m add.m sub.m mul.m div.m result.m 
include $(GNUSTEP_MAKEFILES)/tool.make